name: Build and Push Container Image

on:
  push:
    branches: [main, dev]
    paths:
      - 'docker/Dockerfile'
      - 'docker/claude_magic.py'
      - 'docker/00-claude.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image tags
        id: tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "version_tag=${{ github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "version_tag=${{ github.ref_name }}-${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kub0-ai/jupyterlab-claude:${{ steps.tag.outputs.tag }}
            ghcr.io/kub0-ai/jupyterlab-claude:${{ steps.tag.outputs.version_tag }}
            ghcr.io/kub0-ai/jupyterlab-claude:${{ github.sha }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            IMAGE_TAG=${{ steps.tag.outputs.tag }}
            VERSION=${{ steps.tag.outputs.version }}
          cache-from: type=registry,ref=ghcr.io/kub0-ai/jupyterlab-claude:buildcache
