name: Build Base Image

on:
  push:
    branches: [main]
    paths:
      - 'docker/base/**'
      - 'docker/custom.css'
      - 'docker/longpress.js'
      - 'docker/overrides.json'
      - 'docker/podman-storage-init.sh'
      - 'docker/proxy-helpers.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kub0-ai/jupyterlab-base:latest
